apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: klosetlab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: fastapi
        image: 862012315401.dkr.ecr.ap-northeast-2.amazonaws.com/klosetlab/fastapi:1d6457a8d20d80272660fe6f862fb32af5b67d2e
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: fastapi-secret
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
