apiVersion: apps/v1
kind: Deployment
metadata:
  name: module-chat
  namespace: klosetlab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: module-chat
  template:
    metadata:
      labels:
        app: module-chat
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: node-role
                operator: In
                values: ["app"]
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: module-chat
              topologyKey: kubernetes.io/hostname
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: module-chat
        image: 862012315401.dkr.ecr.ap-northeast-2.amazonaws.com/klosetlab/module-chat:477f0dd10784384fe74408c51a1846f5434890cd
        ports:
        - containerPort: 8081
        envFrom:
        - secretRef:
            name: module-chat-secret
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
