apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: module-chat-ingress
  namespace: klosetlab
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - v3.klosetlab.site
    secretName: klosetlab-tls
  rules:
  - host: v3.klosetlab.site
    http:
      paths:
      - path: /ws
        pathType: Prefix
        backend:
          service:
            name: module-chat-svc
            port:
              number: 8081
